exports.users = [
  {
    username: "Test Man",
    email: "tester@gmail.com",
    password: "$2a$10$W4awb/30e07veV5tVP3WOuDbyI1MrnUf7ORhJmfZ8oA9zh2DyPIUC",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    username: "Test Man2",
    email: "tester2@gmail.com",
    password: "$2a$10$W4awb/30e07veV5tVP3WOuDbyI1MrnUf7ORhJmfZ8oA9zh2DyPIUC",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

exports.records = [
  {
    title: "First Income",
    amount: 2000,
    date: "2022-07-01 06:00:00",
    type: "INCOME",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Second Income",
    amount: 3000,
    date: "2022-07-01 12:00:00",
    type: "INCOME",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Third Income",
    amount: 2500,
    date: "2022-07-02 06:00:00",
    type: "INCOME",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Income4",
    amount: 2500,
    date: "2022-07-02 13:00:00",
    type: "INCOME",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Income5",
    amount: 3000,
    date: "2022-07-02 20:00:00",
    type: "INCOME",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Income5",
    amount: 3000,
    date: "2022-07-02 20:00:00",
    type: "INCOME",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Expense1",
    amount: 5000,
    date: "2022-07-01 11:00:00",
    type: "EXPENSE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Expense2",
    amount: 10000,
    date: "2022-07-02 20:00:00",
    type: "EXPENSE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Today Income1",
    amount: 1000,
    type: "INCOME",
    date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Today Income2",
    amount: 2000,
    type: "INCOME",
    date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Today Income3",
    amount: 3000,
    type: "INCOME",
    date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Today Income4",
    amount: 4000,
    type: "INCOME",
    date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Today Income5",
    amount: 5000,
    type: "INCOME",
    date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Today Income6",
    amount: 6000,
    type: "INCOME",
    date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Today Income7",
    amount: 7000,
    type: "INCOME",
    date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Today Expense1",
    amount: 8000,
    type: "EXPENSE",
    date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Today Expense2",
    amount: 7000,
    type: "EXPENSE",
    date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Today Expense3",
    amount: 6000,
    type: "EXPENSE",
    date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Today Expense4",
    amount: 5000,
    type: "EXPENSE",
    date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Today Expense5",
    amount: 4000,
    type: "EXPENSE",
    date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Today Expense6",
    amount: 3000,
    type: "EXPENSE",
    date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Today Expense7",
    amount: 2000,
    type: "EXPENSE",
    date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Today Expense8",
    amount: 1000,
    type: "EXPENSE",
    date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
